/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package managementtrevel.CustomTripBuilder;

import Asset.SidebarPanel;

import javax.naming.directory.SearchResult;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author ikhlas putra
 */
public class DestinationStep extends javax.swing.JFrame {

    /**
     * Creates new form DestinationStep
     */
    public DestinationStep() {
        initComponents();
    
    setTitle("Destination Step");
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setSize(800, 600);
    setLocationRelativeTo(null);
    setLayout(null);

    // Buat layeredPane
    JLayeredPane layeredPane = getLayeredPane();
    SidebarPanel sidebar = new SidebarPanel();
    sidebar.setBounds(0, 0, 65, getHeight()); // atur ukuran dan posisi sidebar
    layeredPane.add(sidebar, JLayeredPane.POPUP_LAYER); // tambahkan di atas layer default
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        txt_destinasi = new javax.swing.JTextField();
        AkomodasiSummary1 = new javax.swing.JLabel();
        IsiAkomodasi1 = new javax.swing.JLabel();
        tambahBtn5 = new javax.swing.JButton();
        tambahBtn6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BuildStepLabel = new javax.swing.JLabel();
        DestinasiLabel = new javax.swing.JLabel();
        TanggalLabel = new javax.swing.JLabel();
        TransportLabel = new javax.swing.JLabel();
        AkomodasiLabel = new javax.swing.JLabel();
        AkomodasiLabel1 = new javax.swing.JLabel();
        FinalLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BuildStepLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        txtfield_destinasi = new javax.swing.JTextField();
        TambahBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        DetinasiSummary = new javax.swing.JLabel();
        IsiDestinasi = new javax.swing.JLabel();
        tambahBtn2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        title4 = new javax.swing.JLabel();
        title5 = new javax.swing.JLabel();
        NextBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();

        txt_destinasi.setText("Pilih Destinasi");
        txt_destinasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_destinasiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_destinasiFocusLost(evt);
            }
        });
        txt_destinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_destinasiActionPerformed(evt);
            }
        });

        AkomodasiSummary1.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        AkomodasiSummary1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AkomodasiSummary1.setText("Akomodasi :");
        AkomodasiSummary1.setToolTipText("");
        AkomodasiSummary1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        IsiAkomodasi1.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        IsiAkomodasi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IsiAkomodasi1.setText("1. ...");
        IsiAkomodasi1.setToolTipText("");
        IsiAkomodasi1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tambahBtn5.setText("+");
        tambahBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtn5ActionPerformed(evt);
            }
        });

        tambahBtn6.setText("-");
        tambahBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtn6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 460));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        BuildStepLabel.setFont(new java.awt.Font("HelveticaNeueLT Std", 1, 14)); // NOI18N
        BuildStepLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuildStepLabel.setText("Build Steps");

        DestinasiLabel.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        DestinasiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DestinasiLabel.setText("1. Destinasi");

        TanggalLabel.setFont(new java.awt.Font("HelveticaNeueLT Std", 1, 12)); // NOI18N
        TanggalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TanggalLabel.setText("2. Tanggal");
        TanggalLabel.setToolTipText("");
        TanggalLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TransportLabel.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        TransportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TransportLabel.setText("3. Transport ");
        TransportLabel.setToolTipText("");
        TransportLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        AkomodasiLabel.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        AkomodasiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AkomodasiLabel.setText("4. Akomodasi");
        AkomodasiLabel.setToolTipText("");
        AkomodasiLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        AkomodasiLabel1.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        AkomodasiLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AkomodasiLabel1.setText("5. Tambah Kegiatan");
        AkomodasiLabel1.setToolTipText("");
        AkomodasiLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        FinalLabel.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        FinalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FinalLabel.setText("6. Final");
        FinalLabel.setToolTipText("");
        FinalLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DestinasiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuildStepLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TanggalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TransportLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AkomodasiLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AkomodasiLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FinalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(BuildStepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DestinasiLabel)
                .addGap(18, 18, 18)
                .addComponent(TanggalLabel)
                .addGap(18, 18, 18)
                .addComponent(TransportLabel)
                .addGap(18, 18, 18)
                .addComponent(AkomodasiLabel)
                .addGap(18, 18, 18)
                .addComponent(AkomodasiLabel1)
                .addGap(18, 18, 18)
                .addComponent(FinalLabel)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(628, 600));

        BuildStepLabel1.setFont(new java.awt.Font("HelveticaNeueLT Std", 1, 14)); // NOI18N
        BuildStepLabel1.setText("Custom Trip Builder");

        btn_back.setText("< Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Pilih Tanggal");
        title.setToolTipText("");
        title.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtfield_destinasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfield_destinasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfield_destinasiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtfield_destinasiFocusLost(evt);
            }
        });
        txtfield_destinasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_destinasiActionPerformed(evt);
            }
        });

        TambahBtn.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        TambahBtn.setText("+");
        TambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtfield_destinasi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TambahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfield_destinasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TambahBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title1.setFont(new java.awt.Font("HelveticaNeueLT Std", 1, 12)); // NOI18N
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Trip Summary");
        title1.setToolTipText("");
        title1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        DetinasiSummary.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        DetinasiSummary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DetinasiSummary.setText("Tanggal :");
        DetinasiSummary.setToolTipText("");
        DetinasiSummary.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        IsiDestinasi.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        IsiDestinasi.setText("1. ...");
        IsiDestinasi.setToolTipText("");

        tambahBtn2.setText("-");
        tambahBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DetinasiSummary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(IsiDestinasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tambahBtn2)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DetinasiSummary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tambahBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IsiDestinasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        title4.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        title4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title4.setText("Estimasi Harga :");
        title4.setToolTipText("");
        title4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        title5.setFont(new java.awt.Font("HelveticaNeueLT Std", 0, 12)); // NOI18N
        title5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title5.setText("Rp...");
        title5.setToolTipText("");
        title5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(title4, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(title5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title5))
        );

        NextBtn.setText("Next");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back)
                    .addComponent(BuildStepLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BuildStepLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextBtn)
                    .addComponent(BackBtn))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_destinasiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_destinasiFocusGained
        if (txt_destinasi.getText().equals("Pilih Destinasi")) {
            txt_destinasi.setText("");
        }
    }//GEN-LAST:event_txt_destinasiFocusGained

    private void txt_destinasiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_destinasiFocusLost
        if (txt_destinasi.getText().isEmpty()) {
            txt_destinasi.setText("Pilih Destinasi");
        }
    }//GEN-LAST:event_txt_destinasiFocusLost

    private void txt_destinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_destinasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_destinasiActionPerformed

    private void tambahBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahBtn5ActionPerformed

    private void tambahBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahBtn6ActionPerformed

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextBtnActionPerformed

    private void tambahBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahBtn2ActionPerformed

    private void TambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahBtnActionPerformed
        if(txt_destinasi.getText().equals("Pilih Destinasi")){
            JOptionPane.showMessageDialog(null,"Masukkan Destinasi Anda");
            txt_destinasi.requestFocus();
        }else if(txt_tanggal.getText().equals("Pilih Tanggal")){
            JOptionPane.showMessageDialog(null,"Pilih Tanggal Terlebih Dulu");
            txt_tanggal.requestFocus();
        }else if(pilih_travelers.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null,"Pilih Jumlah Travelers Dulu");
            pilih_travelers.requestFocus();
        }else{
            new SearchResult().show();
            this.dispose();
        }
    }//GEN-LAST:event_TambahBtnActionPerformed

    private void txtfield_destinasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_destinasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield_destinasiActionPerformed

    private void txtfield_destinasiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfield_destinasiFocusLost
        if (txt_destinasi.getText().isEmpty()) {
            txt_destinasi.setText("Pilih Destinasi");
        }
    }//GEN-LAST:event_txtfield_destinasiFocusLost

    private void txtfield_destinasiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfield_destinasiFocusGained
        if (txt_destinasi.getText().equals("Pilih Destinasi")) {
            txt_destinasi.setText("");
        }
    }//GEN-LAST:event_txtfield_destinasiFocusGained

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new HomeScreen().show();
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void createRightSidebar() {
        rightSidebar = new JPanel();
        rightSidebar.setBackground(new Color(240, 240, 240));
        rightSidebar.setBorder(BorderFactory.createMatteBorder(0, 2, 0, 0, Color.GRAY));
        rightSidebar.setLayout(new BorderLayout());
        
        // Header panel with toggle button
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setBackground(new Color(220, 220, 220));
        headerPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        JLabel headerLabel = new JLabel("Trip Summary", SwingConstants.CENTER);
        headerLabel.setFont(new Font("HelveticaNeueLT Std", Font.BOLD, 14));
        
        toggleSidebarBtn = new JButton("◀");
        toggleSidebarBtn.setFont(new Font("Arial", Font.BOLD, 12));
        toggleSidebarBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        toggleSidebarBtn.setFocusPainted(false);
        toggleSidebarBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                toggleSidebar();
            }
        });
        
        headerPanel.add(headerLabel, BorderLayout.CENTER);
        headerPanel.add(toggleSidebarBtn, BorderLayout.WEST);
        
        // Content panel
        JPanel contentPanel = new JPanel();
        contentPanel.setLayout(new GridBagLayout());
        contentPanel.setBackground(Color.WHITE);
        contentPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 0, 5, 0);
        
        // Trip summary content
        addSummaryItem(contentPanel, gbc, 0, "Destination:", "Not selected");
        addSummaryItem(contentPanel, gbc, 1, "Date:", "Not selected");
        addSummaryItem(contentPanel, gbc, 2, "Transport:", "Not selected");
        addSummaryItem(contentPanel, gbc, 3, "Accommodation:", "Not selected");
        addSummaryItem(contentPanel, gbc, 4, "Activities:", "None added");
        
        // Add separator
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(20, 0, 20, 0);
        JPanel separator = new JPanel();
        separator.setBackground(Color.LIGHT_GRAY);
        separator.setPreferredSize(new java.awt.Dimension(0, 1));
        contentPanel.add(separator, gbc);
        
        // Total cost section
        gbc.gridy = 6;
        gbc.insets = new Insets(5, 0, 5, 0);
        JLabel totalLabel = new JLabel("Estimated Total:");
        totalLabel.setFont(new Font("HelveticaNeueLT Std", Font.BOLD, 12));
        contentPanel.add(totalLabel, gbc);
        
        gbc.gridy = 7;
        JLabel costLabel = new JLabel("Rp 0");
        costLabel.setFont(new Font("HelveticaNeueLT Std", Font.BOLD, 16));
        costLabel.setForeground(new Color(0, 150, 0));
        contentPanel.add(costLabel, gbc);
        
        // Action buttons
        gbc.gridy = 8;
        gbc.insets = new Insets(30, 0, 10, 0);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
        JButton saveBtn = new JButton("Save Trip");
        saveBtn.setBackground(new Color(70, 130, 180));
        saveBtn.setForeground(Color.WHITE);
        saveBtn.setFont(new Font("HelveticaNeueLT Std", Font.BOLD, 12));
        saveBtn.setFocusPainted(false);
        contentPanel.add(saveBtn, gbc);
        
        gbc.gridy = 9;
        gbc.insets = new Insets(10, 0, 0, 0);
        
        JButton shareBtn = new JButton("Share Trip");
        shareBtn.setBackground(new Color(60, 179, 113));
        shareBtn.setForeground(Color.WHITE);
        shareBtn.setFont(new Font("HelveticaNeueLT Std", Font.BOLD, 12));
        shareBtn.setFocusPainted(false);
        contentPanel.add(shareBtn, gbc);
        
        // Wrap content in scroll pane
        JScrollPane scrollPane = new JScrollPane(contentPanel);
        scrollPane.setBorder(null);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        
        rightSidebar.add(headerPanel, BorderLayout.NORTH);
        rightSidebar.add(scrollPane, BorderLayout.CENTER);
        
        // Set initial position and size
        updateSidebarBounds();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DestinationStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DestinationStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DestinationStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DestinationStep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DestinationStep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AkomodasiLabel;
    private javax.swing.JLabel AkomodasiLabel1;
    private javax.swing.JLabel AkomodasiSummary1;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel BuildStepLabel;
    private javax.swing.JLabel BuildStepLabel1;
    private javax.swing.JLabel DestinasiLabel;
    private javax.swing.JLabel DetinasiSummary;
    private javax.swing.JLabel FinalLabel;
    private javax.swing.JLabel IsiAkomodasi1;
    private javax.swing.JLabel IsiDestinasi;
    private javax.swing.JButton NextBtn;
    private javax.swing.JButton TambahBtn;
    private javax.swing.JLabel TanggalLabel;
    private javax.swing.JLabel TransportLabel;
    private javax.swing.JButton btn_back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton tambahBtn2;
    private javax.swing.JButton tambahBtn5;
    private javax.swing.JButton tambahBtn6;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    private javax.swing.JTextField txt_destinasi;
    private javax.swing.JTextField txtfield_destinasi;
    // End of variables declaration//GEN-END:variables
}
