/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package managementtrevel.Payment;

import managementtrevel.BookingScreen.BookingScreen;
import managementtrevel.TripDetailScreen.TripDetail;

/**
 *
 * @author Bagas Adi
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_namapenumpang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_notelp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_bank = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb_bank1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cb_bank2 = new javax.swing.JComboBox<>();
        btn_bayar = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tf_idreservasi = new javax.swing.JTextField();
        tf_idreservasi1 = new javax.swing.JTextField();
        tf_idreservasi2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tf_namakota = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tf_tanggal = new javax.swing.JTextField();
        tf_durasi = new javax.swing.JTextField();
        tf_tiket = new javax.swing.JTextField();
        tf_admin1 = new javax.swing.JTextField();
        tf_asuransi1 = new javax.swing.JTextField();
        tf_pajak = new javax.swing.JTextField();
        tf_totalpembayaran = new javax.swing.JTextField();
        tf_tiket4 = new javax.swing.JTextField();
        tf_admin = new javax.swing.JTextField();
        tf_asuransi = new javax.swing.JTextField();
        tf_pajak1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Pembayaran");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Informasi Pembayaran");

        tf_namapenumpang.setText("Nama Penumpang");
        tf_namapenumpang.setBorder(null);
        tf_namapenumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_namapenumpangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Informasi Penumpang");

        tf_notelp.setText("Nomor Telepon");
        tf_notelp.setBorder(null);
        tf_notelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_notelpActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Metode Pembayaran");

        cb_bank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Bank BCA", "Bank BNI", "Bank BRI", "Bank Mandiri" }));
        cb_bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bankActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Bank");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("E Wallet");

        cb_bank1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Gopay", "Dana", "OVO", "ShopeePay" }));
        cb_bank1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bank1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Kartu Kredit");

        cb_bank2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Visa", "Mastercard", "JCB" }));
        cb_bank2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bank2ActionPerformed(evt);
            }
        });

        btn_bayar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_bayar.setText("Bayar Sekarang");

        btn_back.setText("< Kembali");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Informasi  Lainnya");

        tf_idreservasi.setText("ID Reservasi");
        tf_idreservasi.setBorder(null);
        tf_idreservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idreservasiActionPerformed(evt);
            }
        });

        tf_idreservasi1.setText("Tanggal Pembayaran");
        tf_idreservasi1.setBorder(null);
        tf_idreservasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idreservasi1ActionPerformed(evt);
            }
        });

        tf_idreservasi2.setText("Status Pembayaran");
        tf_idreservasi2.setBorder(null);
        tf_idreservasi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idreservasi2ActionPerformed(evt);
            }
        });

        jLabel11.setText("ID Reservasi");

        jLabel12.setText("Tanggal Pembayaran");

        jLabel13.setText("Status Pembayaran");

        jLabel14.setText(":");

        jLabel15.setText(":");

        jLabel16.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btn_back)
                            .addGap(94, 94, 94)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(121, 121, 121)
                                    .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cb_bank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cb_bank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cb_bank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)))
                                .addComponent(jLabel10)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tf_namapenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(167, 167, 167)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_idreservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_idreservasi1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_idreservasi2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btn_back))
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tf_namapenumpang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_idreservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_idreservasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_idreservasi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_bank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_bank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_bank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Ringkasan");

        tf_namakota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_namakota.setText("Kota Tujuan");
        tf_namakota.setBorder(null);
        tf_namakota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_namakotaActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        tf_tanggal.setBackground(new java.awt.Color(204, 204, 204));
        tf_tanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_tanggal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_tanggal.setText("Tanggal");
        tf_tanggal.setBorder(null);
        tf_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tanggalActionPerformed(evt);
            }
        });

        tf_durasi.setBackground(new java.awt.Color(204, 204, 204));
        tf_durasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_durasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_durasi.setText("Durasi");
        tf_durasi.setBorder(null);
        tf_durasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_durasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_durasi, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(tf_durasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tf_tiket.setEditable(false);
        tf_tiket.setBackground(new java.awt.Color(255, 255, 255));
        tf_tiket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_tiket.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_tiket.setText("Tiket");
        tf_tiket.setBorder(null);
        tf_tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tiketActionPerformed(evt);
            }
        });

        tf_admin1.setEditable(false);
        tf_admin1.setBackground(new java.awt.Color(255, 255, 255));
        tf_admin1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_admin1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_admin1.setText("Rp...");
        tf_admin1.setBorder(null);
        tf_admin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_admin1ActionPerformed(evt);
            }
        });

        tf_asuransi1.setEditable(false);
        tf_asuransi1.setBackground(new java.awt.Color(255, 255, 255));
        tf_asuransi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_asuransi1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_asuransi1.setText("Rp...");
        tf_asuransi1.setBorder(null);
        tf_asuransi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_asuransi1ActionPerformed(evt);
            }
        });

        tf_pajak.setEditable(false);
        tf_pajak.setBackground(new java.awt.Color(255, 255, 255));
        tf_pajak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_pajak.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_pajak.setText("Pajak");
        tf_pajak.setBorder(null);
        tf_pajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pajakActionPerformed(evt);
            }
        });

        tf_totalpembayaran.setEditable(false);
        tf_totalpembayaran.setBackground(new java.awt.Color(255, 255, 255));
        tf_totalpembayaran.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_totalpembayaran.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_totalpembayaran.setText("Rp...");
        tf_totalpembayaran.setBorder(null);
        tf_totalpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_totalpembayaranActionPerformed(evt);
            }
        });

        tf_tiket4.setEditable(false);
        tf_tiket4.setBackground(new java.awt.Color(255, 255, 255));
        tf_tiket4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_tiket4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_tiket4.setText("Rp...");
        tf_tiket4.setBorder(null);
        tf_tiket4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tiket4ActionPerformed(evt);
            }
        });

        tf_admin.setEditable(false);
        tf_admin.setBackground(new java.awt.Color(255, 255, 255));
        tf_admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_admin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_admin.setText("Admin");
        tf_admin.setBorder(null);
        tf_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_adminActionPerformed(evt);
            }
        });

        tf_asuransi.setEditable(false);
        tf_asuransi.setBackground(new java.awt.Color(255, 255, 255));
        tf_asuransi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_asuransi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_asuransi.setText("Asuransi");
        tf_asuransi.setBorder(null);
        tf_asuransi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_asuransiActionPerformed(evt);
            }
        });

        tf_pajak1.setEditable(false);
        tf_pajak1.setBackground(new java.awt.Color(255, 255, 255));
        tf_pajak1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_pajak1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_pajak1.setText("Rp...");
        tf_pajak1.setBorder(null);
        tf_pajak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pajak1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Total Pembayaran");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(86, 86, 86))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tf_asuransi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_asuransi1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tf_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_admin1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_namakota, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tf_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_tiket4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(tf_pajak, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_pajak1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addComponent(tf_totalpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(36, 36, 36)
                .addComponent(tf_namakota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tiket4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_admin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_asuransi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_asuransi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pajak1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_totalpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_namapenumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_namapenumpangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_namapenumpangActionPerformed

    private void tf_notelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_notelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_notelpActionPerformed

    private void cb_bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_bankActionPerformed

    private void cb_bank1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bank1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_bank1ActionPerformed

    private void cb_bank2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bank2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_bank2ActionPerformed

    private void tf_namakotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_namakotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_namakotaActionPerformed

    private void tf_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tanggalActionPerformed

    private void tf_tiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tiketActionPerformed

    private void tf_durasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_durasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_durasiActionPerformed

    private void tf_admin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_admin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_admin1ActionPerformed

    private void tf_asuransi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_asuransi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_asuransi1ActionPerformed

    private void tf_pajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pajakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pajakActionPerformed

    private void tf_totalpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_totalpembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_totalpembayaranActionPerformed

    private void tf_tiket4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tiket4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tiket4ActionPerformed

    private void tf_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_adminActionPerformed

    private void tf_asuransiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_asuransiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_asuransiActionPerformed

    private void tf_pajak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pajak1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pajak1ActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new BookingScreen().show();
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void tf_idreservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idreservasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idreservasiActionPerformed

    private void tf_idreservasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idreservasi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idreservasi1ActionPerformed

    private void tf_idreservasi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idreservasi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idreservasi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new Payment().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JComboBox<String> cb_bank;
    private javax.swing.JComboBox<String> cb_bank1;
    private javax.swing.JComboBox<String> cb_bank2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tf_admin;
    private javax.swing.JTextField tf_admin1;
    private javax.swing.JTextField tf_asuransi;
    private javax.swing.JTextField tf_asuransi1;
    private javax.swing.JTextField tf_durasi;
    private javax.swing.JTextField tf_idreservasi;
    private javax.swing.JTextField tf_idreservasi1;
    private javax.swing.JTextField tf_idreservasi2;
    private javax.swing.JTextField tf_namakota;
    private javax.swing.JTextField tf_namapenumpang;
    private javax.swing.JTextField tf_notelp;
    private javax.swing.JTextField tf_pajak;
    private javax.swing.JTextField tf_pajak1;
    private javax.swing.JTextField tf_tanggal;
    private javax.swing.JTextField tf_tiket;
    private javax.swing.JTextField tf_tiket4;
    private javax.swing.JTextField tf_totalpembayaran;
    // End of variables declaration//GEN-END:variables
}
